### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by vladfaust** [formeronyxframework/onyx-cli#1]
Hello, @lancer-s7s8, are you around?

**Comment by lancer-s7s8** [comment]
Hey @vladfaust , here but the project is unmaintained for various reasons. I might also delete it in the next couple days. Let me know if you had some ideas/suggestions in mind. Thanks!

**Comment by lancer-s7s8** [comment]
@vladfaust sure, I can do it any time. I will see if I can give you all admin privileges on the organization, then you can remove me and either continue using it, or delete it and rename yours to this name. Let you know soon if/when I manage to add you.

**Comment by lancer-s7s8** [comment]
@vladfaust I've added you (was quite simple). Feel free to delete this repository and remove me from the organization. Thanks.

**Comment by vladfaust** [comment]
I’ve accepted it! Gonna be home in an hour, will do the transfer and leave another comment 😏

**Comment by vladfaust** [comment]
Alright, I did it. I could not delete your code for myself (moral issues 😅), so pull the trigger youself if you want. 

Thank you very much, @lancer-s7s8, I truly appreciate it. I'd like to put your name (Lance Round) and a link of your choice in the framework's credits as a thank you. Let me know what link you'd like to use, if any - here or by e-mail.

**Comment by lancer-s7s8** [comment]
@vladfaust No need for any credit, just do nice work :) I appreciate all your contributions to the Crystal ecosystem. Thanks!
